trigger:
  batch: true
  branches:
      include:
          - master

pool:
  name: Hosted Ubuntu 1604

variables:
  bot.image: 'carlhugo/ogechobot'
  bot.imageName: 'ogechobot'
  bot.sshEndpoint: 'Google Cloud Bots'
  bot.dockerRegistryEndpoint: 'Docker Hub'
  bot.envFile: 'ogechobot.env'

resources:
  repositories:
    - repository: shared
      type: github
      name: for-the-new-order/BuildTemplates
      endpoint: for-the-new-order

jobs:
  - template: BuildAndDeployBot.yml@shared
    parameters:
      bot:
        image: ''
        imageName: ''
        sshEndpoint: ''
        dockerRegistryEndpoint: ''
        envFile: ''